### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by ai** [gucong3000/postcss-styled#16]
ChangeLog is mandatory for all PostCSS projects ;)
https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md

**Comment by ai** [comment]
Found `0.9` release and don’t know is it safe to update the version in my project (according to SemVer it could contains breaking changes)

**Comment by gucong3000** [comment]
Changelog has added here:
https://github.com/gucong3000/postcss-styled/releases

**Comment by ai** [comment]
Great, thanks
