### ISSUE TITLE
Not CSS-in-JS was parsed

### ISSUE THREAD

**Issue by ai** [gucong3000/postcss-styled#34]
I started to use Stylelint in our project and got 

```
popups/balance.js
 64:39  ✖  Expected a trailing semicolon
```

error on this code:

```
      h(Note, [
        h(TextFormat, {
          links: [`#card:${ projectId }`],
          text: t.note
        })
      ]),
```

Seems like parser try to parse any CSS in template strings

**Comment by gucong3000** [comment]
> Seems like parser try to parse any CSS in template strings
Yes, it is.

This is a known issue, and using [postcss-jsx](https://github.com/gucong3000/postcss-jsx) instead of `postcss-styled` can solve this problem.

[postcss-jsx](https://github.com/gucong3000/postcss-jsx) use [Babel@7](https://babeljs.io) to parse javascript context.

**Comment by ai** [comment]
Here is our Stylelint config:

```json
{
  "plugins": [
    "stylelint-order"
  ],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ]
}
```

Should we ask Stylelint team to not use `postcss-styled`? Will template string work with `postcss-jsx`? (Example show only object notation).

**Comment by gucong3000** [comment]
> Should we ask Stylelint team to not use postcss-styled?

https://github.com/stylelint/stylelint/pull/3506
After merge this PR, `postcss-syntax` will switch to use `postcss-jsx` to extract template strings in js source.

**Comment by gucong3000** [comment]
`postcss-jsx` was [add to stylelint](https://github.com/stylelint/stylelint/pull/3506)
