### ISSUE TITLE
Work with Buffer

### ISSUE THREAD

**Issue by ai** [gucong3000/postcss-styled#9]
`postcss.parse()` can accept `Buffer` in addition to string. it just call `css = css.toString()`. It is very useful since `fs.readFile` returns `Buffer`.

I think we should put `css = css.toString()` to `postcss-styled` to have same behaviour. 

@gucong3000 I try to use your awesome parser on my project, be ready for more issues :D

**Comment by gucong3000** [comment]
Done in v0.3.0
